version: '2'

services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    command: sh -c './wait-for db:5432 -- python3 app.py'
    volumes:
      - .:/usr/src/app
    ports:
      - "8888:8888"
    depends_on:
      - db
