version: '3'

services:
  db:
    image: postgres:9.4
    env_file:
      - ./deployment/variables.env
    volumes:
      - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    env_file:
      - ./deployment/variables.env
    command: sh -c '/usr/local/bin/wait-for.sh db:5432 -- python3 ./app.py'
    volumes:
      - ./merchantcustomer:/usr/src/app/
    ports:
      - "8888:8888"
    depends_on:
      - db
